style = dict(style_name    = 'tradingview',
             base_mpl_style= 'fast',
             marketcolors  = {'candle'   : {'up': '#26a69a', 'down': '#ef5350'},  
                              'edge'     : {'up': '#26a69a', 'down': '#ef5350'},  
                              'wick'     : {'up': '#26a69a', 'down': '#ef5350'},  
                              'ohlc'     : {'up': '#26a69a', 'down': '#ef5350'},
                              'volume'   : {'up': '#26a69a', 'down': '#ef5350'},  
                              'vcedge'   : {'up': '#26a69a', 'down': '#ef5350'},  
                              'vcdopcod' : False,
                              'alpha'    : 1.0,
                             },
             mavcolors     = ['#ffc201','#ff10ff','#cd0468','#1f77b4',
                              '#ff7f0e','#2ca02c','#40e0d0'],
             y_on_right    = True,
             gridcolor     = None,
             gridstyle     = '--',
             facecolor     =  None,
             rc            = [ ('axes.grid','True'),
                               #('axes.grid.axis' , 'y'),
                               ('axes.edgecolor'  , 'grey' ),
                               ('axes.titlecolor','red'),
                               ('figure.titlesize', 'x-large' ),
                               ('figure.titleweight','semibold'),
                               ('figure.facecolor', 'white' ),
                             ],
             base_mpf_style = 'tradingview'
            )
